spring:
  datasource:
    dynamic:
      primary: mysql_one #主数据源
      datasource:
        mysql_one:
          url: jdbc:mysql://localhost:3306/dynamic_one?serverTimezone=GMT%2B8
          username: root
          password: 112233
        mysql_two:
          url: jdbc:mysql://localhost:3306/dynamic_two?serverTimezone=GMT%2B8
          username: root
          password: 112233
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9999


mybatis-plus:
  mapper-locations: classpath*:mapper/xml/**/*.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.gty.domain
  #项目启动会检查xml配置存在(只在开发时候打开)
  check-config-location: true
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: false
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #表名下划线命名默认true
      table-underline: true
      #id类型
      id-type: INPUT
      #数据库类型
      db-type: mysql